# Generated by Django 4.0.5 on 2022-07-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_group_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video',
        ),
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='g/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='u/avatars/'),
        ),
        migrations.CreateModel(
            name='FileMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='m/files/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.message')),
            ],
            options={
                'db_table': 'file_messages',
            },
        ),
    ]
