# Generated by Django 4.0.5 on 2022-07-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_message_audio_remove_message_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='is_pending',
        ),
        migrations.AddField(
            model_name='couple',
            name='user1_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couple',
            name='user2_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
