# Generated by Django 4.0.5 on 2022-07-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_couple_is_pending_couple_user1_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
